server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
  redis:
    host: localhost #Redis服务器地址
    database: 0 #Redis数据库索引（默认为0）
    port: 6379 #Redis服务器连接端口
    password: #Redis服务器连接密码（默认为空）
    timeout: 300ms #连接超时时间（毫秒）

minio:
  endpoint: http://127.0.0.1:9000 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥

logging:
  level:
    root: info